#   Build images: docker-compose build
#      Start app: docker-compose up scrapper

version: "3.9"
services:
  scrapper:
    build:
      context: .
    ports:
      - "5000:5000"
    volumes:
      - .:/src